NER: InfoIDF Class Reference
InfoIDF Class Reference
#include <InfoIDF.h>
Public Member Functions
InfoIDF ()
InfoIDF incrDF ()
InfoIDF incrCF ()
void calculateExpectedIDF (int totalDocs)
int getCf () const
int getDf () const
double getExpectedIdf () const
Private Attributes
int cf
int df
double expectedIDF
Detailed Description
Definition at line 11 of file InfoIDF.h.
Constructor & Destructor Documentation
InfoIDF::InfoIDF ()
Definition at line 9 of file InfoIDF.cpp.
References cf, df, and expectedIDF.
Member Function Documentation
void InfoIDF::calculateExpectedIDF (int totalDocs)
Directly calculates the expected IDF of each word
Returns:
as per poisson distribution lambda^k e^(-lambda)/k! (mean)^0 = 1
Definition at line 27 of file InfoIDF.cpp.
References cf, and expectedIDF.
Referenced by ResidualIDF::printSortedIDFs().
int InfoIDF::getCf () const [inline]
Definition at line 37 of file InfoIDF.h.
References cf.
int InfoIDF::getDf () const [inline]
Definition at line 41 of file InfoIDF.h.
References df.
Referenced by ResidualIDF::printSortedIDFs().
double InfoIDF::getExpectedIdf () const [inline]
Definition at line 45 of file InfoIDF.h.
References expectedIDF.
Referenced by ResidualIDF::printSortedIDFs().
InfoIDF InfoIDF::incrCF ()
Increments the Frequency of word
Returns:
Definition at line 21 of file InfoIDF.cpp.
References cf.
Referenced by ResidualIDF::calculateInfo(), and ResidualIDF::calculateInfoWiki().
InfoIDF InfoIDF::incrDF ()
Increments the document Frequency
Returns:
Definition at line 14 of file InfoIDF.cpp.
References df.
Referenced by ResidualIDF::calculateInfo(), and ResidualIDF::calculateInfoWiki().
Member Data Documentation
int InfoIDF::cf [private]
Definition at line 13 of file InfoIDF.h.
Referenced by calculateExpectedIDF(), getCf(), incrCF(), and InfoIDF().
int InfoIDF::df [private]
Definition at line 14 of file InfoIDF.h.
Referenced by getDf(), incrDF(), and InfoIDF().
double InfoIDF::expectedIDF [private]
Definition at line 16 of file InfoIDF.h.
Referenced by calculateExpectedIDF(), getExpectedIdf(), and InfoIDF().
The documentation for this class was generated from the following files:
src/ResidualIDF/InfoIDF.h
src/ResidualIDF/InfoIDF.cpp