NER: Page Class Reference
Page Class Reference
#include <WikiReader.h>
Public Member Functions
Page ()
vector< string > getLines () const
string getTitle () const
void appendLine (string line)
string getRawText () const
void setLines (const vector< string > &lines)
void setTitle (const string &title)
Private Attributes
vector< string > lines
string title
Detailed Description
Definition at line 20 of file WikiReader.h.
Constructor & Destructor Documentation
Page::Page ()
Definition at line 45 of file WikiReader.cpp.
Member Function Documentation
void Page::appendLine (string line) [inline]
Definition at line 34 of file WikiReader.h.
Referenced by WikiReader::getNextDoc().
vector<string> Page::getLines () const [inline]
Definition at line 27 of file WikiReader.h.
Referenced by ResidualIDF::calculateInfoWiki().
string Page::getRawText () const [inline]
Definition at line 37 of file WikiReader.h.
string Page::getTitle () const [inline]
Definition at line 31 of file WikiReader.h.
void Page::setLines (const vector< string > & lines) [inline]
Definition at line 40 of file WikiReader.h.
void Page::setTitle (const string & title) [inline]
Definition at line 44 of file WikiReader.h.
Referenced by WikiReader::getNextDoc().
Member Data Documentation
vector<string> Page::lines [private]
Definition at line 22 of file WikiReader.h.
string Page::title [private]
Definition at line 23 of file WikiReader.h.
The documentation for this class was generated from the following files:
src/ResidualIDF/WikiReader.h
src/ResidualIDF/WikiReader.cpp