NER: ResidualIDF Class Reference
ResidualIDF Class Reference
#include <ResidualIDF.h>
Public Member Functions
ResidualIDF ()
void calculateInfo (string dir)
void calculateInfoWiki (const char *wikiPath)
void printSortedIDFs (ofstream &out)
Private Attributes
map< string, double > wordMap
map< string, InfoIDF > wordVals
int totalDocs
Detailed Description
Definition at line 20 of file ResidualIDF.h.
Constructor & Destructor Documentation
ResidualIDF::ResidualIDF () [inline]
Constructor for Residual IDF class
Definition at line 29 of file ResidualIDF.h.
Member Function Documentation
void ResidualIDF::calculateInfo (string dir)
Calculates IDF info for the documents in the specified directory
Parameters:
[in] dir directory path to docs
Returns:
Definition at line 44 of file ResidualIDF.cpp.
References InfoIDF::incrCF(), and InfoIDF::incrDF().
void ResidualIDF::calculateInfoWiki (const char * wikiPath)
Calculates IDF info for the wiki text
Parameters:
[in] dir Path to wiki text
Returns:
Definition at line 11 of file ResidualIDF.cpp.
References Page::getLines(), WikiReader::getNextDoc(), InfoIDF::incrCF(), InfoIDF::incrDF(), and WikiReader::isEOF().
Referenced by main().
void ResidualIDF::printSortedIDFs (ofstream & out)
Definition at line 104 of file ResidualIDF.cpp.
References InfoIDF::calculateExpectedIDF(), InfoIDF::getDf(), InfoIDF::getExpectedIdf(), and mapComp().
Referenced by main().
Member Data Documentation
int ResidualIDF::totalDocs [private]
Definition at line 24 of file ResidualIDF.h.
map<string,double> ResidualIDF::wordMap [private]
Definition at line 22 of file ResidualIDF.h.
map<string,InfoIDF> ResidualIDF::wordVals [private]
Definition at line 23 of file ResidualIDF.h.
The documentation for this class was generated from the following files:
src/ResidualIDF/ResidualIDF.h
src/ResidualIDF/ResidualIDF.cpp